apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: DBPORT
      value: "3306"
imagePullSecrets:
- name: ecr-secret
      
