apiVersion: apps/v1
kind: Deployment               
metadata:
  name: mysql-deployment
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  replicas: 1                  
  selector:
    matchLabels:
      app: mysql
  template:                    
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: mysql
        image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/mysql:v1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password" 