apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "localhost"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "root"
      imagePullSecrets:
      - name: ecr-secret
          
          
