apiVersion: apps/v1
kind: Deployment                   
metadata:
  name: websapp-deployment
  namespace: webapp-ns
spec:
  replicas: 3                     
  selector:
    matchLabels:
      app: employees 
  template:                       
    metadata:
      labels:
        app: employees 
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: webapp
        image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/webapp:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBPWD
          value: "password"
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPORT
          value: "3306"