apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/webapp:v2
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.8"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "root"
      imagePullSecrets:
      - name: ecr-secret
          
