apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: mysql-service
            - name: DBUSER
              value: root
            - name: DBPWD
              value: root
            - name: DBPORT
              value: "3306"
            - name: DATABASE
              value: employees
      imagePullSecrets:
        - name: ecr-secret
