apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 601387777514.dkr.ecr.us-east-1.amazonaws.com/webapp:v2
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-service"  
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"  
    - name: DBPWD
      value: "root"
  imagePullSecrets:
  - name: ecr-secret
      
